name: Node CI
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test
